import type { StoreCategory } from "@/types/design";

export type ShopifyCategoryGroup = {
  group: StoreCategory;
  categories: string[];
  keywords: string[];
};

export const SHOPIFY_CATEGORY_GROUPS: ShopifyCategoryGroup[] = [
  {
    group: "fashion",
    categories: [
      "Streetwear & Urban Fashion",
      "Luxury Fashion",
      "Minimalist Clothing",
      "Activewear & Gym Apparel",
      "Swimwear",
      "Lingerie & Sleepwear",
      "Vintage Clothing",
      "Plus Size Fashion",
      "Maternity Wear",
      "Formal & Occasion Wear",
      "Workwear & Office Fashion",
      "Modest Fashion",
      "Festival Clothing",
      "Custom Apparel",
      "Seasonal Fashion",
      "Resort Wear",
      "Bridal & Wedding Fashion",
      "Denim & Basics",
      "Loungewear",
      "Luxury Outerwear",
      "Uniforms & Team Apparel",
      "Athleisure",
      "Anime Streetwear",
      "Techwear Fashion",
      "Golf Apparel",
      "Luxury Modest Couture",
      "Men's Fashion",
      "Women's Fashion",
      "T-Shirts & Graphic Tees",
      "Hoodies & Sweatshirts",
      "Jackets & Coats",
      "Jeans & Denim Shop",
      "Sports Jerseys",
      "School Uniforms",
      "Work Uniforms",
      "Sustainable Fashion",
      "Petite Fashion",
      "Tall Fashion",
      "Luxury Knitwear",
      "Cashmere & Knitwear",
      "Leather Jackets & Apparel",
      "Linen Clothing",
      "Street Luxury",
      "Korean Fashion",
      "Japanese Fashion",
      "Y2K Fashion",
      "Gothic Fashion",
      "Boho Fashion",
      "Adaptive Clothing",
      "Luxury Streetwear",
      "Performance Workwear",
      "Luxury Basics",
      "Athletic Recovery Wear",
      "Running Apparel",
      "Cycling Apparel",
      "Tennis Apparel",
      "Contemporary Tailoring",
      "Festival Streetwear",
      "Premium Basics",
      "Capsule Wardrobe",
      "Designer Dresses"
    ],
    keywords: [
      "fashion","clothing","streetwear","luxury fashion","minimalist clothing","apparel","activewear","gym apparel","swimwear","lingerie","sleepwear",
      "vintage","plus size","maternity","formal wear","occasion wear","office fashion","workwear","modest fashion","festival clothing","custom apparel","seasonal fashion",
      "wardrobe","dress","denim","tops","bottoms","resort wear","bridal","wedding dress","loungewear","outerwear","athleisure","jersey","anime streetwear","techwear fashion","golf apparel","abaya","modest couture","mens fashion","womens fashion","graphic tees","hoodies","jackets","coats","jeans","sports jerseys","school uniforms","work uniforms", "luxury basics", "running apparel", "cycling apparel", "tennis apparel", "contemporary tailoring", "capsule wardrobe", "designer dresses", "premium basics", "festival streetwear", "recovery wear",
    ],
  },
  {
    group: "kids",
    categories: [
      "Kids & Baby Clothing",
      "Baby Essentials",
      "Toys & Games",
      "Educational Toys",
      "School Supplies for Kids",
      "Nursery & Baby Room Decor",
      "Party Supplies",
      "Baby Gear",
      "Kids Footwear",
      "Teen Fashion",
      "Baby Feeding Essentials",
      "Strollers & Carriers",
      "Kids Bedroom Decor",
      "Craft Kits",
      "STEM Learning Kits",
      "Back to School",
      "Kids Books",
      "Pretend Play",
      "Montessori Toys",
      "Kids Sportswear",
      "Baby Skincare",
      "Baby Furniture",
      "Kids Furniture",
      "Baby Toys",
      "Outdoor Toys",
      "Board Games",
      "Puzzles",
      "Kids Electronics",
      "Baby Bottles & Feeding",
      "Diapers & Baby Care",
      "Baby Monitors",
      "Kids Swimwear",
      "Kids Party Wear",
      "Baby Bedding",
      "Nursery Lighting",
      "Learning Tablets for Kids",
      "Ride-On Toys",
      "Dolls & Dollhouses",
      "Building Blocks",
      "Plush Toys",
      "Kids Art Supplies",
      "Kids Lunch Boxes",
      "Kids Backpacks",
      "Kids Sports Equipment",
      "Kids Furniture & Storage",
      "Kids Gadgets",
      "Baby Nursery Essentials",
      "Kids Room Decor",
      "Learning Games",
      "Kids Outdoor Play",
      "Baby Bath & Care",
      "Kids Party Supplies",
      "Family Travel Gear",
      "Kids Reading Corner"
    ],
    keywords: [
      "kids","kid","children","childrens","baby","baby clothing","baby essentials","toys","games","educational toys","school supplies","nursery","party supplies","baby gear","teen fashion","toddler","boys","girls","playwear",
      "stroller","carrier","feeding","craft kits","stem toys","school","pretend play","kids books","crib","newborn","montessori","kids sportswear","baby skincare","baby furniture","kids furniture","baby toys","outdoor toys","board games","puzzles","kids electronics","baby bottles","diapers", "kids room decor", "family travel gear", "learning games", "baby bath care", "kids outdoor play", "kids gadgets", "baby nursery essentials", "kids furniture storage",
    ],
  },
  {
    group: "shoes",
    categories: [
      "Shoes & Sneakers",
      "Boots & Hiking Footwear",
      "Sandals & Slides",
      "Luxury Footwear",
      "Running Shoes",
      "Skate Shoes",
      "Kids Footwear",
      "Basketball Shoes",
      "Golf Shoes",
      "Trail Running Shoes",
      "Performance Cleats",
      "Leather Dress Shoes",
      "Loafers & Everyday Slip-Ons",
      "Barefoot & Minimal Shoes",
      "Dance Shoes",
      "Recovery Slides",
      "Women's Heels",
      "Women's Flats",
      "Men's Sneakers",
      "Women's Sneakers",
      "Work Boots",
      "Safety Shoes",
      "School Shoes",
      "Soccer Cleats",
      "Tennis Shoes",
      "Hiking Boots",
      "Running Spikes",
      "Cycling Shoes",
      "Hiking Sandals",
      "Platform Shoes",
      "Slippers & House Shoes",
      "Orthopedic Shoes",
      "Nursing Shoes",
      "Chef & Kitchen Shoes",
      "Waterproof Boots",
      "Cowboy Boots",
      "Snow Boots",
      "Luxury Sneakers",
      "Trail Hiking Shoes",
      "Trail Sandals",
      "Minimal Running Shoes",
      "Lifestyle Sneakers",
      "Luxury Loafers",
      "Outdoor Footwear",
      "Court Shoes",
      "Slides & Recovery",
      "Formal Footwear",
      "Kids Running Shoes",
      "Travel Shoes"
    ],
    keywords: [
      "shoe","shoes","sneaker","sneakers","footwear","boots","hiking footwear","sandals","slides","luxury footwear","running shoes","skate shoes","trail shoes",
      "basketball shoes","golf shoes","cleats","dress shoes","loafers","slip-ons","football boots","barefoot shoes","dance shoes","recovery slides","heels","flats","mens sneakers","womens sneakers","work boots","safety shoes","school shoes","soccer cleats","tennis shoes", "lifestyle sneakers", "luxury loafers", "trail sandals", "minimal running shoes", "slides recovery", "travel shoes", "outdoor footwear", "court shoes",
    ],
  },
  {
    group: "accessories",
    categories: [
      "Handbags & Accessories",
      "Jewelry & Watches",
      "Travel Accessories",
      "Eyewear",
      "Phone Cases & Wearable Accessories",
      "Office Accessories",
      "Wallets & Small Leather Goods",
      "Watches",
      "Luxury Accessories",
      "Pet Accessories",
      "Cycling Accessories",
      "Motorcycle Accessories",
      "Automotive Accessories",
      "Belts & Scarves",
      "Tech Cases & Sleeves",
      "Desk Accessories",
      "Keychains & Charms",
      "Fine Jewelry",
      "Men's Accessories",
      "Designer Sunglasses",
      "Laptop Bags",
      "Travel Organizers",
      "Piercing Jewelry",
      "Cars & Automotive",
      "Car Dealership & Auto Marketplace",
      "Electric Vehicle Accessories",
      "Car Parts & Accessories",
      "Tires & Wheels",
      "Car Audio & Entertainment",
      "Auto Detailing Products",
      "Motorcycle Parts & Gear",
      "Helmets & Riding Gear",
      "Classic Watches",
      "Luxury Watches",
      "Eyeglasses & Optical",
      "Sunglasses",
      "Reading Glasses",
      "Backpacks",
      "Luggage & Suitcases",
      "Briefcases & Business Bags",
      "Luxury Handbags",
      "Wallets & Cardholders",
      "Belts",
      "Hats & Caps",
      "Scarves & Wraps",
      "Hair Accessories",
      "Travel Backpacks",
      "Camera Bags",
      "Watch Straps",
      "Smartwatch Bands",
      "Phone Cases",
      "Luxury Pens",
      "Umbrellas",
      "Eyewear Accessories",
      "Fine Jewelry & Gold",
      "Pearl Jewelry",
      "Luxury Pens & Desk Goods",
      "Travel Luggage",
      "Laptop Sleeves",
      "Gaming Accessories",
      "Phone Accessories",
      "Camera Accessories",
      "Automotive Lifestyle",
      "Smart Home Accessories"
    ],
    keywords: [
      "accessory","accessories","handbag","handbags","jewelry","watches","watch","travel accessories","eyewear","phone cases","wearable accessories","office accessories","wallet","leather goods","luxury accessories","pet accessories","cycling accessories","motorcycle accessories","automotive accessories","bag","bags",
      "belt","scarf","tech case","sleeve","charms","fine jewelry","bracelet","necklace","ring","mens accessories","designer sunglasses","laptop bag","travel organizer","piercing jewelry","car","cars","automotive","auto marketplace","car dealership","vehicle","vehicles","electric vehicle","ev accessories","car parts","auto parts","tires","wheels","car audio","auto detailing","motorcycle parts","helmet","riding gear","classic watch","luxury watch","eyeglasses","optical store","sunglasses","reading glasses","backpack","luggage","suitcase","briefcase", "pearl jewelry", "luxury pens", "travel luggage", "laptop sleeves", "gaming accessories", "phone accessories", "camera accessories", "automotive lifestyle", "smart home accessories",
    ],
  },
  {
    group: "beauty",
    categories: [
      "Skincare",
      "Makeup & Cosmetics",
      "Haircare",
      "Perfume & Fragrance",
      "Men's Grooming",
      "Spa & Wellness",
      "Nail Care",
      "Salon Tools",
      "Beauty Devices",
      "Clean Beauty",
      "Personal Care",
      "K-Beauty",
      "Dermatology & Clinical Skincare",
      "Bath & Body",
      "Organic Beauty",
      "Self-Care Gifts",
      "Barber Supplies",
      "Wellness Supplements",
      "Scalp Care",
      "Beauty Tools & Brushes",
      "Lip Care",
      "Dental & Oral Care",
      "Body Care",
      "Deodorants",
      "Shaving & Razors",
      "Hair Styling Products",
      "Hair Extensions & Wigs",
      "False Eyelashes",
      "Contact Lens Care",
      "Massage & Recovery Products",
      "Korean Skincare",
      "Men’s Grooming",
      "Hair Care",
      "Curly Hair Care",
      "Hair Styling Tools",
      "Sunscreen & SPF",
      "Beauty Gift Sets",
      "Spa & Massage Essentials",
      "Facial Tools & Devices",
      "Clinical Skincare",
      "Beauty Supplements",
      "Hair Tools",
      "Facial Devices",
      "Fragrance Discovery",
      "Body Mist",
      "Bar Soap & Wash",
      "Spa Equipment",
      "Professional Makeup"
    ],
    keywords: [
      "beauty","skincare","skin care","makeup","cosmetics","haircare","hair care","perfume","fragrance","grooming","spa","wellness","nail care","salon tools","beauty devices","clean beauty","personal care","serum","cleanser","barber",
      "k-beauty","clinical skincare","dermatology","bath and body","organic beauty","self-care","soap","lotion","supplement beauty","scalp care","beauty brushes","lip care","oral care","dental care","body care","deodorant","razor","shaving","hair styling","hair extensions","wigs","false eyelashes","contact lens","massage recovery", "spf", "sunscreen", "beauty supplements", "hair tools", "facial devices", "fragrance discovery", "body mist", "professional makeup",
    ],
  },
  {
    group: "food",
    categories: [
      "Supplements & Vitamins",
      "Organic & Natural Products",
      "Coffee & Tea",
      "Bakery & Desserts",
      "Chocolate & Candy",
      "Snacks & Specialty Food",
      "Meal Prep & Healthy Food",
      "Restaurant Merchandise",
      "Beverages & Juices",
      "Wine & Gourmet Gifts",
      "Meal Kits",
      "Pet Food & Treats",
      "Food Subscription Boxes",
      "Farmers Market Goods",
      "Sauces & Condiments",
      "Protein & Fitness Nutrition",
      "Asian Grocery",
      "Craft Beverages",
      "Frozen Foods",
      "Prepared Meals",
      "Specialty Matcha",
      "Protein Snacks",
      "Zero-Sugar Drinks",
      "Hot Sauces",
      "Seafood & Fresh Fish",
      "Frozen Seafood",
      "Fish Market",
      "Sushi & Japanese Food",
      "Meat & Butcher Shop",
      "Chicken & Poultry",
      "Fresh Produce",
      "Fruit & Vegetable Market",
      "Dairy & Cheese",
      "Rice & Grains",
      "Noodles & Pasta",
      "Breakfast & Cereals",
      "Ice Cream & Frozen Desserts",
      "Healthy Drinks",
      "Milk Tea & Boba",
      "Energy Drinks",
      "Bottled Water",
      "Seafood Delivery",
      "Fresh Salmon",
      "Shellfish & Prawns",
      "Meat Delivery",
      "Gourmet Cheese",
      "Specialty Coffee",
      "Loose Leaf Tea",
      "Chocolate & Confectionery",
      "Healthy Snacks",
      "Frozen Food",
      "Organic Grocery",
      "Asian Groceries",
      "Spices & Seasonings",
      "Premium Olive Oil",
      "Fresh Bread & Pastries",
      "Butcher & Meat",
      "Bakery & Bread",
      "Organic Produce",
      "Desserts & Sweets",
      "Gourmet Pantry"
    ],
    keywords: [
      "food","supplements","vitamins","organic","natural products","coffee","tea","bakery","desserts","chocolate","candy","snacks","specialty food","meal prep","healthy food","restaurant merchandise","beverages","juice","wine","gourmet gifts","meal kits","pet food","treats","subscription boxes","farmers market","sauce","pantry","kitchen","recipe","condiment",
      "protein","nutrition","grocery","craft beverages","frozen food","prepared meals","tea shop","cafe","matcha","protein snacks","zero-sugar drinks","hot sauce","seafood","fresh fish","fish market","frozen seafood","sushi","japanese food","butcher","meat shop","chicken","poultry","fresh produce","fruit market","vegetable market","dairy","cheese","rice","grains","noodles","pasta","cereal","ice cream","milk tea","boba","energy drinks","bottled water", "coffee and tea", "healthy snacks", "organic produce", "gourmet pantry",
    ],
  },
  {
    group: "home",
    categories: [
      "Furniture",
      "Home Decor",
      "Kitchen & Dining",
      "Bedding & Bedroom",
      "Lighting & Lamps",
      "Plants & Gardening",
      "Books & Stationery",
      "Art Prints & Posters",
      "Office & Desk Setup",
      "Bathroom Essentials",
      "Storage & Organization",
      "DIY & Hardware",
      "Craft Room Supplies",
      "Holiday Decor",
      "Smart Storage",
      "Outdoor Furniture",
      "Rugs & Textiles",
      "Tableware",
      "Pet Furniture",
      "Smart Home Decor",
      "Wall Art",
      "Home Fragrance",
      "Aroma Diffusers",
      "Minimal Desk Decor",
      "Smart Lighting",
      "Sofas & Couches",
      "Beds & Mattresses",
      "Bedroom Furniture",
      "Dining Tables & Chairs",
      "Cabinets & Shelving",
      "TV Stands & Media Units",
      "Kitchen Appliances",
      "Refrigerators & Freezers",
      "Ovens & Ranges",
      "Air Fryers",
      "Microwaves",
      "Coffee Machines",
      "Blenders & Food Processors",
      "Rice Cookers",
      "Cookware & Pots",
      "Kitchen Knives",
      "Vacuum Cleaners",
      "Washing Machines & Dryers",
      "Air Conditioners",
      "Electric Fans",
      "Water Purifiers",
      "Home Cleaning Supplies",
      "Living Room Furniture",
      "Mattresses",
      "Bedding & Linens",
      "Rugs & Carpets",
      "Curtains & Blinds",
      "Bathroom Furniture",
      "Home Office Decor",
      "Wall Art & Prints",
      "Smart Furniture",
      "Sofas & Sectionals",
      "Beds & Bed Frames",
      "Dining Furniture",
      "Home Office Furniture",
      "Storage Solutions",
      "Wall Decor"
    ],
    keywords: [
      "home","furniture","home decor","kitchen","dining","bedding","bedroom","lighting","lamps","plants","gardening","books","stationery","art prints","posters","office","desk setup","bathroom","storage","organization","diy","hardware","craft room","holiday decor","smart storage","workspace","interior","linen","decor",
      "outdoor furniture","rug","textile","tableware","wall art","home fragrance","sofa","table","chair","aroma diffuser","desk decor","smart lighting","sofa","sofas","couch","couches","bed","beds","mattress","mattresses","bedroom furniture","dining table","cabinet","shelving","tv stand","kitchen appliances","refrigerator","freezer","oven","range","air fryer","microwave","coffee machine","blender","food processor","rice cooker","cookware","pots","kitchen knives","vacuum cleaner","washing machine","dryer","air conditioner","electric fan","water purifier","cleaning supplies", "dining furniture", "office furniture", "rugs", "wall decor", "storage solutions", "bathroom essentials",
    ],
  },
  {
    group: "outdoor",
    categories: [
      "Outdoor & Camping",
      "Fishing Equipment",
      "Sports Equipment",
      "Cycling & Bike Gear",
      "Travel & Adventure Gear",
      "Hiking Equipment",
      "Water Sports",
      "Winter Sports Gear",
      "Fitness Equipment",
      "Pet Outdoor Gear",
      "Garden Tools",
      "Climbing Gear",
      "Running Gear",
      "Tactical Equipment",
      "Trail Essentials",
      "Surf & Beach Gear",
      "Ski & Snowboard",
      "Hunting & Field Gear",
      "Pickleball Gear",
      "Padel Gear",
      "Overlanding Equipment",
      "Basketball Equipment",
      "Football & Soccer Gear",
      "Volleyball Gear",
      "Badminton Gear",
      "Tennis Gear",
      "Boxing & Martial Arts Gear",
      "Gym Equipment",
      "Home Fitness Equipment",
      "Bicycles",
      "E-Bikes",
      "Scooters",
      "Kayaks & Paddle Sports",
      "Golf Equipment",
      "Baseball Gear",
      "Rugby Gear",
      "Cricket Gear",
      "Table Tennis Gear",
      "Swimming Gear",
      "Diving & Snorkeling",
      "Camping Furniture",
      "Camping Cookware",
      "Hiking Backpacks",
      "Tents & Shelters",
      "Sleeping Bags",
      "Outdoor Grills",
      "Running Accessories",
      "Camping Gear",
      "Cycling Equipment",
      "Fishing Gear",
      "Travel Gear",
      "Adventure Photography",
      "Overlanding Gear"
    ],
    keywords: [
      "outdoor","camping","fishing equipment","sports equipment","cycling","bike gear","travel gear","adventure gear","hiking equipment","water sports","winter sports","fitness equipment","pet outdoor gear","garden tools","ski","alpine","snow","techwear","winter","mountain",
      "climbing","running gear","tactical","trail","surf","beach gear","snowboard","hunting","pickleball","padel","overlanding","basketball equipment","football gear","soccer gear","volleyball","badminton","tennis gear","boxing","martial arts","gym equipment","home fitness","bicycle","bicycles","e-bike","ebike","scooter","kayak","paddle sports", "camping gear", "cycling equipment", "fishing gear", "climbing gear", "overlanding gear",
    ],
  },
  {
    group: "tech",
    categories: [
      "Electronics",
      "Smartphones & Accessories",
      "Gaming Accessories",
      "PC Components",
      "Smart Home Products",
      "Cameras & Photography",
      "Audio & Headphones",
      "Wearables & Smartwatches",
      "Laptops & Tablets",
      "Monitors & Displays",
      "Streaming Equipment",
      "Drones & Tech Toys",
      "Charging & Power",
      "3D Printing",
      "AR / VR Gear",
      "Mechanical Keyboards",
      "Creator Gear",
      "Office Tech",
      "Security Cameras",
      "Networking Devices",
      "Portable Gaming",
      "Microphones & Recording",
      "Smart Appliances",
      "Smart Rings",
      "Sim Racing Gear",
      "NAS & Storage",
      "Mobile Filmmaking Gear",
      "Smartphones",
      "iPhone & iOS Phones",
      "Android Phones",
      "Refurbished Phones",
      "Phone Accessories",
      "Phone Chargers & Power Banks",
      "Phone Repair Parts",
      "Tablets & iPads",
      "Televisions & Smart TVs",
      "Projectors",
      "Home Theater & Soundbars",
      "Desktop Computers",
      "Gaming PCs",
      "Graphics Cards",
      "Computer Monitors",
      "Printers & Scanners",
      "Wi-Fi Routers",
      "Computer Storage & SSDs",
      "Action Cameras",
      "Dash Cameras",
      "Security Systems",
      "Robotics & Smart Gadgets",
      "Smartwatches",
      "Fitness Trackers",
      "Earbuds",
      "Portable Speakers",
      "E-Readers",
      "Mini PCs",
      "Workstation PCs",
      "Webcams",
      "Capture Cards",
      "Computer Mice",
      "Gaming Keyboards",
      "Docking Stations",
      "Uninterruptible Power Supplies",
      "Phone Photography Accessories",
      "Laptops & Computers",
      "Tablets & E-Readers",
      "Smartphones & Mobile",
      "TV & Home Entertainment",
      "Cameras & Drones",
      "Gaming PCs & Consoles",
      "Smart Home",
      "Networking",
      "Computer Peripherals"
    ],
    keywords: [
      "tech","electronics","smartphones","smartphone accessories","gaming accessories","pc components","smart home","cameras","photography","audio","headphones","wearables","smartwatches","laptops","tablets","monitors","displays","streaming equipment","drones","charging","power","3d printing","ar","vr","computer","pc","gadget","devices","phone","laptop","monitor","component",
      "mechanical keyboard","creator gear","office tech","security camera","networking","portable gaming","microphone","recording","smart appliances","console","smart ring","sim racing","nas storage","mobile filmmaking","smartphone","smartphones","iphone","ios phone","android phone","refurbished phone","phone accessories","phone charger","power bank","phone repair","ipad","tablet","smart tv","television","tv","projector","soundbar","home theater","desktop computer","gaming pc","graphics card","gpu","computer monitor","printer","scanner","wifi router","router","ssd","computer storage","action camera","dash camera","security system","robotics", "ereader", "home entertainment", "camera", "drone", "peripherals",
    ],
  },
];

export const ALL_SHOPIFY_CATEGORIES = Array.from(new Set(SHOPIFY_CATEGORY_GROUPS.flatMap((item) => item.categories)));
export const TOTAL_SHOPIFY_CATEGORIES = ALL_SHOPIFY_CATEGORIES.length;

export const EXTRA_50_SHOPIFY_CATEGORIES = ALL_SHOPIFY_CATEGORIES.slice(-50) as readonly string[];
